checking direct download

diff --git a/.github/workflows/cron_job.yml b/.github/workflows/cron_job.yml
--- a/.github/workflows/cron_job.yml
+++ b/.github/workflows/cron_job.yml
@@ -35,12 +35,23 @@ jobs:
           echo "Downloading trigger binary from GitHub release..."
           LATEST_TAG=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/vikshrogit/trigger/releases/latest | jq -r .tag_name)
           echo "$LATEST_TAG"
-          curl -L \
-            -H "Authorization: token $GH_TOKEN" \
-            -o "${{ env.BIN_PATH }}" \
-            "https://github.com/vikshrogit/trigger/releases/download/${LATEST_TAG}/${{ env.BIN_NAME }}"
-          chmod +x "${{ env.BIN_PATH }}"
-          ls trigger-bin
+          ASSET_ID=$(curl -s -H "Authorization: token $GH_PAT" \
+            https://api.github.com/repos/vikshrogit/trigger/releases/tags/$LATEST_TAG \
+            | jq ".assets[] | select(.name == \"${{ env.BIN_NAME }}\") | .id")
+
+          if [ -z "$ASSET_ID" ]; then
+            echo "❌ Error: Asset '${{ env.BIN_NAME }}' not found in release $TAG"
+            exit 1
+          fi
+
+            # ---- DOWNLOAD ----
+           echo "⬇️ Downloading asset ID: $ASSET_ID ${{ env.BIN_NAME }}"
+           curl -L \
+            -H "Authorization: token $GH_PAT" \
+            -H "Accept: application/octet-stream" \
+            https://api.github.com/repos/vikshrogit/trigger/releases/assets/$ASSET_ID \
+            -o "${{ env.BIN_PATH }}"
+           ls trigger-bin
           cat ${{ env.BIN_PATH }}
 
       - name: Run trigger binary with URL
